# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false


julia:
  - 1.5
  - 1.4
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly

script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/ZhouZhuofei/NumericalAnalysis.jl"))'
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage = true)'
after_success:

  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Coveralls.submit(process_folder())'
