name = "NumericalAnalysis"
uuid = "fb18ad0a-c577-441c-b4b0-b42a431f6d4f"
authors = ["Zhuofei Zhou"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
